### ISSUE TITLE
No access to drives other than root

### ISSUE THREAD

**Issue by K0-RR** [alescdb/mailviewer#4]
I have one pendrive and two HDDs mounted, but they are not visible in the app.

**Comment by alescdb** [comment]
This is a flatpak/sandbox issue, you can give it access to `host` :
```
flatpak override --user --filesystem=host io.github.alescdb.mailviewer
```

You might also need usb access :
```
flatpak override --user --device=usb io.github.alescdb.mailviewer
```

**Comment by alescdb** [comment]
You can also use [flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) to set permissions
